json.id product.id
json.name product.name
json.price product.price
json.tax product.tax.round(2)
json.total product.total.round(2)
json.image_url product.image_url
json.description product.description
json.is_discounted? product.is_discounted?
json.supplier_id product.supplier_id